
spring:
  application:
    name: platform_show
  datasource:
    url: jdbc:mysql://47.92.80.128:3306/platform
    username: platform
    password: DfErP7TFemMixE7f
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: 47.92.80.128
      port: 6379
      username: default
      password: redis_PCpmaT
  security:
    jwt:
      key: 'my-platform-key'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    flow:
      period: 3
      limit: 200
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  servlet.multipart.max-file-size: 20MB  #服务器接受最大文件大小
  servlet.multipart.max-request-size: 20MB #服务器单次请求大小
Model:
  URL: http://47.92.80.128:8000

minio:
  endpoint: http://47.92.80.128:9000
  access-key: JAm1aUN2PHwmgOPAEO07
  secret-key: 41LwF9eotVRVcgQBN9uCgfxVkvY0JX3GFS9TP5W1
  bucket-name: platform